/* Shared public navigation, footer, and dropdown behavior. */
(function () {
    document.documentElement.setAttribute('data-theme', 'light');
    document.documentElement.style.colorScheme = 'light';
    try { localStorage.removeItem('bobmanuel-theme'); } catch (_) { /* Storage can be unavailable. */ }
    if (!document.querySelector('link[rel="icon"]')) {
        const favicon = document.createElement('link'); favicon.rel='icon'; favicon.type='image/svg+xml'; favicon.href='assets/icons/bobmanuel-mark.svg'; document.head.appendChild(favicon);
    }
    const page = document.body.dataset.page || 'home'; const homePrefix = page === 'home' ? '' : 'index.html';
    const headerHost=document.querySelector('[data-shared-header]');
    if(headerHost){headerHost.innerHTML=`<nav class="navbar" id="navbar"><div class="nav-container"><a href="index.html" class="nav-logo" aria-label="BOBMANUEL home"><img class="brand-mark" src="assets/icons/bobmanuel-mark.svg" alt="" width="32" height="32"><span>BOBMANUEL.</span></a><ul class="nav-menu" id="navMenu"><li><a href="index.html" class="nav-link ${page==='home'?'active':''}">Home</a></li><li><a href="about.html" class="nav-link ${page==='about'?'active':''}">About</a></li><li><a href="${homePrefix}#skills" class="nav-link">Skills</a></li><li><a href="projects.html" class="nav-link ${page==='projects'?'active':''}">Projects</a></li><li><a href="contact.html" class="nav-link ${page==='contact'?'active':''}">Contact</a></li></ul><div class="nav-actions"><div class="nav-auth-controls nav-login-link" data-auth-controls><a href="login.html" class="btn-admin-login">Login</a><a href="register.html" class="btn-admin-login auth-register-link">Register</a></div><button class="nav-toggle" id="navToggle" aria-label="Toggle navigation" aria-controls="navMenu" aria-expanded="false"><span></span><span></span><span></span></button></div></div></nav>`;}
    const footerHost=document.querySelector('[data-shared-footer]');
    if(footerHost){footerHost.innerHTML=`<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><div class="footer-logo"><img class="brand-mark" src="assets/icons/bobmanuel-mark.svg" alt="" width="34" height="34">BOBMANUEL.</div><p><strong>Tamunodiepriye Sogbeye Bobmanuel</strong><br>Full-Stack Developer • Graphic Designer • Video Editor<br>Building complete digital solutions and creative content from Nigeria.</p><div class="footer-socials"><a href="https://wa.me/2349112403944" target="_blank" rel="noopener" aria-label="WhatsApp"><img src="assets/icons/whatsapp.svg" alt="" width="18" height="18"></a><a href="https://www.tiktok.com/@itsglitchronin.vfx" target="_blank" rel="noopener" aria-label="TikTok"><img src="assets/icons/tiktok.svg" alt="" width="18" height="18"></a><a href="https://www.instagram.com/scott_vfx?igsh=MXMyMjVibTJ5MHhyeg%3D%3D&amp;igsi=MXMyMjVibTJ5MHhyeg%3D%3D" target="_blank" rel="noopener" aria-label="Instagram"><img src="assets/icons/instagram.svg" alt="" width="18" height="18"></a><a href="https://youtube.com/@scottedits-f2g" target="_blank" rel="noopener" aria-label="YouTube"><img src="assets/icons/youtube.svg" alt="" width="18" height="18"></a></div></div><div class="footer-col"><h4>Navigate</h4><ul><li><a href="index.html">Home</a></li><li><a href="about.html">About</a></li><li><a href="projects.html">Projects</a></li><li><a href="design.html">Design</a></li><li><a href="videos.html">Edits</a></li></ul></div><div class="footer-col"><h4>More</h4><ul><li><a href="education.html">Education</a></li><li><a href="cv.html">CV</a></li><li><a href="services.html">Services</a></li><li><a href="contact.html">Contact</a></li><li><a href="terms.html">Terms &amp; Conditions</a></li><li><a href="privacy.html">Privacy Policy</a></li></ul></div><div class="footer-col"><h4>Contact</h4><ul><li><a href="mailto:dbobmanuel29@gmail.com">dbobmanuel29@gmail.com</a></li><li><a href="https://wa.me/2349112403944" target="_blank" rel="noopener">WhatsApp</a></li><li><a href="login.html">Login</a></li></ul></div></div><div class="footer-bottom"><p>&copy; 2026 Tamunodiepriye Sogbeye Bobmanuel. All rights reserved.</p></div></div></footer>`;}
})();
import('./auth-state.js').catch(error=>console.error('Authentication state module failed to load:',error.message));